### PR TITLE
Allow raw SPARQL queries

### PR DESCRIPTION
**Pull request by arendsee**
This PR gives the user the option to submit SPARQL queries as raw strings.

### CODE REVIEW

**Comment by arendsee** [comment]
Any thoughts on whether this PR is useful?

I have a larger PR I'll in the pipeline that adds support for a bunch of currently missing SPARQL functions. I'll push it after this PR is resolved.

**Comment by robstewart57** [comment]
I assume you've got a use case for submitting raw sparql queries?

Happy to accept this PR, thanks for submitting!

I think meaningful names, e.g. `selectQueryRaw`, `askQueryRaw` etc might be more intuitive than `selectQuery'` etc.

**Comment by arendsee** [comment]
Agreed on the meaningful names, I've changed that in the last commit.

The DSL adds a lot to SPARQL. The typechecking and extra programmability are
wonderful. However, there are a few general cases where I would want to use raw
SPARQL: 

 1. The user is providing the SPARQL code. A user might be submitting their own
    SELECT queries or the program might use SPARQL configuration files.

 2. The programmer is building their own DSL or generating their own SPARQL
    code. They may want to reuse the HTTP handling of `hsparql`. This also
    might be used as a hack to add support for non-standard SPARQL flavors.

 3. The programmer wants to develop and test the SPARQL query outside the
    Haskell context. For example, a programmer might start designing a complex
    SPARQL query in their favorite semantic IDE. They may begin with a SPARQL
    example shamelessly copied from Stackoverflow. Once they are happy with the
    query, they can port it into their Haskell program and ensure it works
    within the Haskell context as a raw query. Finally, they can translate it
    into the `hsparql` DSL and generalize the query as needed.

**Comment by robstewart57** [comment]
Your use cases are convincing.

PR merged, thanks.

**Comment by arendsee** [comment]
Thank you!

**Pull request merged**
