### PR TITLE
Added a DSL supporting property paths from SPARQL 1.1

### PR DESCRIPTION
**Pull request by koslambrou**
Added property path expression and ensured that it can be used inside `triple_` or similar functions.

Wasn't too sure about the plumbing in order to integrate property path expression with existing code. Feedback would be appreciated.

Also, the DSL used to create property path could probably be enhanced. If you think there are better symbols to use, I'll change it.

### CODE REVIEW

**Comment by robstewart57** [comment]
@koslambrou Nice!

I hadn't previously considered support for property paths in SPARQL 1.1.

Perhaps just one more commit for haddock documentation to include the W3C URL documenting property paths: https://www.w3.org/TR/sparql11-query/#propertypaths 

I'll merge this, thanks again.

**Comment by robstewart57** [comment]
@koslambrou There is currently a conflict in `tests/Database/HSparql/QueryGeneratorTest.hs`, preventing me from merging automatically.

**Comment by koslambrou** [comment]
@robstewart57 Cool :) I'll resolve the conflict. Where should I put the W3C URL ? On top of the `PropertyPathExpr` data type ?

**Comment by robstewart57** [comment]
@koslambrou 

> On top of the PropertyPathExpr data type ?

Sounds good. Thanks.

**Comment by koslambrou** [comment]
@robstewart57 Conflict resolved. Added w3c URL documentation in the module header.

**Comment by robstewart57** [comment]
@koslambrou Excellent, thank you very much. I'll merge this.

**Pull request merged**
